#!/usr/bin/env bash
# The MIT License (MIT)
#	
# ant-switch-frontend - glue between KiwiSDR and antenna switches
#
# This is part of KiwiSDR antenna switch extension
#
# Copyright (c) 2018 Kari Karvonen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

VERSION=0.4

BACKENDFILE=/root/extensions/ant_switch/backends/ant-switch-backend
if [ -x $BACKENDFILE ]; then
	. $BACKENDFILE
else
	echo "Cannot load or execute backend file $BACKENDFILE"
	exit 1
fi

AntSW_SelectBackend() {
	valid_backend_selected=0
	while [ "$valid_backend_selected" == 0 ]; do
		echo "Available antenna switch backends:"
		for backend in /root/extensions/ant_switch/backends/ant-switch-backend-*; do
		    name=`basename $backend`
		    name=`echo $name | sed 's/ant-switch-backend-//'`
		    echo $name
		done
		echo ""
		if [[ -z "${BACKEND// }" ]]; then
            BACKEND="ms-s7-web"
		fi
		echo -n "which backend you would like to use (default: $BACKEND) ? "
		read selected_backend
		if [[ -z "${selected_backend// }" ]]; then
			 selected_backend=$BACKEND
		fi
		if [ -r "/root/extensions/ant_switch/backends/ant-switch-backend-$selected_backend" ]; then
			echo "Selected backend: $selected_backend";
			valid_backend_selected=1
			rm /root/extensions/ant_switch/backends/ant-switch-backend
			ln -s /root/extensions/ant_switch/backends/ant-switch-backend-$selected_backend /root/extensions/ant_switch/backends/ant-switch-backend
		else
			echo "Invalid selection $selected_backend. Try again."
		fi
	done
}

AntSW_ShowUsage() {
	echo "ant-switch-frontend - glue between KiwiSDR and antenna switches"
	echo "Version $VERSION Copyright (c) 2018 Kari Karvonen"
	echo ""
	echo "Usage: $0 command"
    echo ""
	echo "Basic antenna switching commands"
	for s in 1 2 3 4 5 6 7 8; do
        echo "$s  = Switch to antenna $s"
	done
	echo "g  = Ground all antennas"
	echo "tg = Ground all antennas. Alias to g."

	echo ""
	echo "Status query commands"
	echo "s  = Status. Show currently selected antennas"
	echo "q  = Query. Alias to status"
	echo ""
	echo "Advanced antenna switching commands"
	echo "+x = Antenna mixing. Add simultanious antenna x"
	echo "-x = Antenna mixing. Remove simultanous antenna x"
	echo "tx = Antenna mixing. Toggle simultanous antenna x"
	echo "     Example: t2 = toggles Antenna 2 state on/off"
	echo ""
	echo "bs = select backend"
	echo "bi = backend information. Show selected backend"
	echo "     and it's configuration / help"
	echo "h = help"
}


case $1 in
	1|2|3|4|5|6|7|8)
		AntSW_Initialize
        AntSW_GroundAll
		AntSW_SelectAntenna $1
		;;
	+1|+2|+3|+4|+5|+6|+7|+8)
		AntSW_Initialize
		antadd=${1//+} 
		AntSW_SelectAntenna $antadd
		;;
	-1|-2|-3|-4|-5|-6|-7|-8)
		AntSW_Initialize
		antremove=${1//-} 
		AntSW_DeSelectAntenna $antremove
		;;
	t1|t2|t3|t4|t5|t6|t7|t8)
		AntSW_Initialize
        anttoggle=${1//t}
		AntSW_ToggleAntenna $anttoggle
		;;
	tg|g)
		AntSW_Initialize
		AntSW_GroundAll
		;;
	s|q)
		AntSW_Initialize
		AntSW_ShowSelected
		;;
	bi)
		AntSW_ShowBackend
		;;
    bs)
        AntSW_SelectBackend
        ;;
	h|"")
		AntSW_ShowUsage
		;;

	*)
		echo "Invalid command \"$1\""
		echo ""
		echo "See help"
		echo "$0 h"
		;;
esac
