#!/usr/bin/env bash
#
# The MIT License (MIT)
#
# ms-s7-web-installer - installer for ms-s7-web                                   
#
# Copyright (c) 2016 Kari Karvonen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE

function valid_ip()
{
    local  ip=$1
    local  stat=1

    if [[ $ip =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
        OIFS=$IFS
        IFS='.'
        ip=($ip)
        IFS=$OIFS
        [[ ${ip[0]} -le 255 && ${ip[1]} -le 255 \
            && ${ip[2]} -le 255 && ${ip[3]} -le 255 ]]
        stat=$?
    fi
    return $stat
}

GetMS7web () {
	if [ -z "$1" ]
	then
		# zero legth
		sleep 1
	else
		REPLY=`$curlexec $CURLOPTS $1`
		if [ "x$REPLY" == "x" ]; then
			# failed. Let's try again.
			REPLY=`$curlexec $CURLOPTS $1`
		fi
		if [ "x$REPLY" == "x" ]; then
			# failed again. One more shot.
			REPLY=`$curlexec $CURLOPTS $1`
		fi
	fi
}

echo "Welcome to MS-S7-WEB ant_switch extension installer"
echo ""

if [ "x`which curl`" == "x" ]; then
	echo "curl not found. Do you want to install it now (y/n) ?"
	read ok
	if [ "x$ok" == "xy" ]; then
		apt-get install curl
		if [ "x`which curl`" == "x" ]; then
			echo "Installation failed. Installation aborted."
			exit 1
		fi
	else
		echo "Curl not installed. Installation aborted."
		exit 1
	fi
fi
CONFFILE=/etc/default/ms-s7-web
CURLOPTS=" --silent --connect-timeout 1"
curlexec=`which curl`

echo "Please enter IP address of your MS-S7-WEB ?"
read IPADDRESS
if valid_ip $IPADDRESS;  then 
	# check that ms-s7-web is working
	GetMS7web "http://$IPADDRESS/io.cgi"
	if [ "x$REPLY" == "x" ]; then
		echo "No reply from MS-S7-WEB at address $IPADDRESS."
		echo "Please your network."
		echo "Installation aborted."
		exit 1
	fi
	echo "Connection to MS-S7-WEB at $IPADDRESS worked OK."
	echo "# KiwiSDR MS-S7-WEB ant_switch extension" > $CONFFILE
	echo "IPADDRESS=$IPADDRESS" >> $CONFFILE
	if [ -r $CONFFILE ]; then
		echo "Created configuration file $CONFFILE"
	else
		echo "Configuration file $CONFFILE creation failed."
		echo "Installation aborted."
		exit 1
	fi
	echo "Copying ant switch files..."
	cp -varf extensions/ant_switch/ /root/Beagle_SDR_GPS/extensions/
	cp -varf extensions/ant_switch /root/Beagle_SDR_GPS/web/extensions/
	cp ms-s7-web /usr/local/bin
	chmod a+rx /usr/local/bin/ms-s7-web
	echo "Rebuilding KiwiSDR"
	cd /root/Beagle_SDR_GPS
	make clean
	make
	make install
	echo "Restarting KiwiSDR"
	./m stop
	./m start
	echo "Installation finished."

else 
	echo "Invalid IP address. Installation aborted."
	exit 1
fi
