#!/usr/bin/env bash
# The MIT License (MIT)
#	
# ant-switch-backend-snaptekk - snaptekk backend for antenna switch
#
# This is part of KiwiSDR antenna switch extension
#
# Copyright (c) 2017 Kari Karvonen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

VERSION=0.1
SNAPTEKK_URL="http://192.168.1.96:9999"
CURLEXEC=/usr/bin/curl
CURLOPTS=" --silent --connect-timeout 1"

AntSW_ShowBackend() {
	echo "ant-switch-backend-snaptekk version $VERSION"
	echo "More info: https://github.com/OH1KK/KiwiSDR-antenna-switch-extension/blob/master/docs/ant-switch-backend-snaptekk.txt"
}

AntSW_Initialize() {
	# This function initalises extension. You can leave empty
	:
}

AntSW_GroundAll() {
	# This function grounds all antennas
	# no return value
	:
}

AntSW_SelectAntenna() {
	# This function selects antenna (turn on)
	# Only one antenna
	# Antenna to select is on variable $1
	# no return value
	$CURLEXEC $CURLOPTS $SNAPTEKK_URL/switch/$1
}

AntSW_DeSelectAntenna() {
        # This function deselects antenna (turn off)
	# Antenna to deleselct is on variable $1
        # Only one antenna
        # no return value
	:
}

AntSW_ToggleAntenna() {
        # This function toggles antenna
 	# if on, then off
	# if off, then on
	# Antenna to toogle is on variable $1
        # Only one antenna
        # no return value
	:
}

AntSW_ShowSelected() {
        # This function show relected antennas
        # returns a string
 	# Selected antennas: 1
	# or comma separated list
        # Selected antennas: 1,2,3,4

	# reply is json string {“Status”:{”0”,”0”, ”1”,”0”,”0”,”0”, ”0”,”0”}}
	reply=`$CURLEXEC $CURLOPTS $SNAPTEKK_URL/status`
	reply='{"Status":{"0","0","1","0","0","0","0","0"}}'
	digits=`echo $reply | sed 's/[^0-1]*//g'`
        for s in 0 1 2 3 4 5 6 7; do
		thisbit=${digits:${s}:1}
		if [ "x$thisbit" == "x1" ]; then
			selectedantennas="${selectedantennas}$(($s+1)),"
			antennafound=$(($antennafound+1))
		fi
	done
	thisbits=${digits:0:8}
	if [ "x$thisbits" == "x00000000" ]; then
		# All antenna inputs are grounded
		antennafound=1
		selectedantennas="g,"
	fi
        selectedantennas=${selectedantennas::-1}
	echo -n "Selected antennas: "
	echo $selectedantennas
}
