#!/usr/bin/env bash
# The MIT License (MIT)
#	
# example-backend - example  script to KiwiSDR antenna switch extension
#
# Copyright (c) 2017 Kari Karvonen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

VERSION=0.1

ant_switch_ShowUsage() {
	echo "beagle-gpio-control"
	echo "Version $VERSION Copyright (c) 2017 Kari Karvonen"
	echo ""
	echo "Usage: $0 command"
        echo ""
	echo "Basic antenna switching commands"
	for s in 1 2 3 4 5 6 7; do
	        echo "$s  = Switch to antenna $s"
	done
	echo "g  = Ground all antennas"
	echo "tg = Ground all antennas. Alias to g."

	echo ""
	echo "Status query commands"
	echo "s  = Status. Show currently selected antennas"
	echo "q  = Query. Alias to status"
	echo ""
	echo "Advanced antenna switching commands"
	echo "+x = Antenna mixing. Add simultanious antenna x"
	echo "-x = Antenna mixing. Remove simultanous antenna x"
	echo "tx = Antenna mixing. Toggle simultanous antenna x"
	echo "     Example: t2 = toggles Antenna 2 state on/off"
	echo ""
}

ant_switch_GroundAll() {
	# Write here code to ground all antennas
}

ant_switch_SelectAntenna() {
	# Write here code to select antenna
	# Antenna number is in variable $1 (number 1 to 7)
}

ant_switch_DeSelectAntenna() {
	# Write here code to deselect antenna
	# Antenna number is in variable $1 (number 1 to 7)
}

ant_switch_ToggleAntenna() {
	# Write here code to switch antenna on/off 
	# Antenna number is in variable $1 (number 1 to 7)
	# Read antenna state, and then do ant_switch_SelectAntenna or ant_switch_DeSelectAntenna
}

ant_switch_ShowSelected() {
	# Write here code to read antenna status
	# Selected antennas should be comma separated list 
	# Selected antennas: 1,2,5
	
	selectedantennas=1,2,5

	# Return value
	echo -n "Selected antennas: "
	echo $selectedantennas
}

case $1 in
	1|2|3|4|5|6|7)
                ant_switch_GroundAll
		ant_switch_SelectAntenna $1
		;;
	+1|+2|+3|+4|+5|+6|+7)
		antadd=${1//+} 
		ant_switch_SelectAntenna $antadd
		;;
	-1|-2|-3|-4|-5|-6|-7)
		antremove=${1//-} 
		ant_switch_DeSelectAntenna $antremove
		;;
	t1|t2|t3|t4|t5|t6|t7)
                anttoggle=${1//t}
		ant_switch_ToggleAntenna $anttoggle
		;;
	tg|g)
		ant_switch_GroundAll
		;;
	s|q)
		ant_switch_ShowSelected
		;;
	*)
		ant_switch_ShowUsage
		;;
esac
