#!/usr/bin/env bash
# The MIT License (MIT)
#	
# beagle-gpio-backend - backend script to antenna switch extension. Uses Beaglebone GPIOs
#
# Copyright (c) 2017 Kari Karvonen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

VERSION=0.1

BeagleGPIO_ShowUsage() {
	echo "beagle-gpio-backend"
	echo "Version $VERSION Copyright (c) 2017 Kari Karvonen"
	echo ""
	echo "Usage: $0 command"
        echo ""
	echo "Basic antenna switching commands"
	for s in 1 2 3 4 5 6 7; do
	        echo "$s  = Switch to antenna $s"
	done
	echo "g  = Ground all antennas"
	echo "tg = Ground all antennas. Alias to g."

	echo ""
	echo "Status query commands"
	echo "s  = Status. Show currently selected antennas"
	echo "q  = Query. Alias to status"
	echo ""
	echo "gi  = GPIO initialize. Initializes GPIO pins 70 - 76"
	echo "gs =  GPIP Shutdown. Shutdown GPIO pins 70 - 76."
	echo ""
	echo "Advanced antenna switching commands"
	echo "+x = Antenna mixing. Add simultanious antenna x"
	echo "-x = Antenna mixing. Remove simultanous antenna x"
	echo "tx = Antenna mixing. Toggle simultanous antenna x"
	echo "     Example: t2 = toggles Antenna 2 state on/off"
	echo ""
}

BeagleGPIO_check_environment() {
	# Make sure only root can run our script
	if [[ $EUID -ne 0 ]]; then
		echo "This script must be run as root" 1>&2
		exit 1
	fi
        for GPIOPIN in 70 71 72 73 74 75 76; do
	        VAL=`cat /sys/class/gpio/gpio${GPIOPIN}/value 2>/dev/null` 
		if [ "x$VAL" == "x" ]; then
			echo "Error. GPIO pin $GPIOPIN is not initalized."
			echo "Please initalize GPIO pins first"
			echo "$0 gi"
			exit 1
		fi
	done
}

BeagleGPIO_Init() {
	for GPIOPIN in 70 71 72 73 74 75 76; do
		echo $GPIOPIN > /sys/class/gpio/export
		echo out > /sys/class/gpio/gpio${GPIOPIN}/direction
	done
}

BeagleGPIO_Shutdown() {
	for GPIOPIN in 70 71 72 73 74 75 76; do
		echo $GPIOPIN > /sys/class/gpio/unexport
	done
}


BeagleGPIO_GroundAll() {
	for s in 1 2 3 4 5 6 7; do
		BeagleGPIO_DeSelectAntenna $s
	done
}

BeagleGPIO_SelectAntenna() {
	ANT=$((69+$1))
	echo 1 > /sys/class/gpio/gpio${ANT}/value
}

BeagleGPIO_DeSelectAntenna() {
	ANT=$((69+$1))
        echo 0 > /sys/class/gpio/gpio${ANT}/value 
}

BeagleGPIO_ToggleAntenna() {
	ANT=$((69+$1))
	# Read antenna status
	VAL=`cat /sys/class/gpio/gpio${GPIOPIN}/value`
	if [ "x$VAL" == "x0" ]; then
		BeagleGPIO_SelectAntenna $1
	else
		BeagleGPIO_DeSelectAntenna $1 
	fi
}

BeagleGPIO_ShowSelected() {
	# Read antenna status
	selectedantennas=''
	antennafound=0
	for GPIOPIN in 70 71 72 73 74 75 76; do
	        VAL=`cat /sys/class/gpio/gpio${GPIOPIN}/value`
		if [ "x$VAL" == "x1" ]; then
			selectedantennas="${selectedantennas}$(($GPIOPIN-69)),"
			antennafound=$(($antennafound+1))
		fi
	done
	if [ "x$selectedantennas" == "x" ]; then
		# All antenna inputs are grounded
		antennafound=1
		selectedantennas="g,"
	fi
	selectedantennas=${selectedantennas::-1}

	echo -n "Selected antennas: "
	echo $selectedantennas
}

case $1 in
	1|2|3|4|5|6|7)
		BeagleGPIO_check_environment
                BeagleGPIO_GroundAll
		BeagleGPIO_SelectAntenna $1
		;;
	+1|+2|+3|+4|+5|+6|+7)
		BeagleGPIO_check_environment
		antadd=${1//+} 
		BeagleGPIO_SelectAntenna $antadd
		;;
	-1|-2|-3|-4|-5|-6|-7)
		BeagleGPIO_check_environment
		antremove=${1//-} 
		BeagleGPIO_DeSelectAntenna $antremove
		;;
	t1|t2|t3|t4|t5|t6|t7)
		BeagleGPIO_check_environment
                anttoggle=${1//t}
		BeagleGPIO_ToggleAntenna $anttoggle
		;;
	tg|g)
		BeagleGPIO_check_environment
		BeagleGPIO_GroundAll
		;;
	s|q)
		BeagleGPIO_check_environment
		BeagleGPIO_ShowSelected
		;;
	gi)
		BeagleGPIO_Init
		;;
	gs)
		BeagleGPIO_Shutdown
		;;
	*)
		BeagleGPIO_ShowUsage
		;;
esac
